/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tyfcxy_SoundAuth_AudioIn */

#ifndef _Included_tyfcxy_SoundAuth_AudioIn
#define _Included_tyfcxy_SoundAuth_AudioIn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tyfcxy_SoundAuth_AudioIn
 * Method:    Populate_Table
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tyfcxy_SoundAuth_AudioIn_Populate_1Table
  (JNIEnv *, jclass);

/*
 * Class:     tyfcxy_SoundAuth_AudioIn
 * Method:    DFT
 * Signature: ([S[I)I
 */
JNIEXPORT jint JNICALL Java_tyfcxy_SoundAuth_AudioIn_DFT
  (JNIEnv *, jclass, jshortArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
