//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundAuth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundAuth.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
